### PR TITLE
Suggested improvements

### PR DESCRIPTION
**Pull request by breathbath**

### CODE REVIEW

**Comment by Metabor** [comment]
There a some conflicts.
Also will need a while for checking what is all in this lucky bag.
Maybe splitting the PR up into the different parts will help (also to do discussion).

**Comment by made7** [comment]
Splitting would be not so easy I wanted to provide it as a collection of ideas)

**Comment by Metabor** [comment]
OK, then I will cherry pick the parts that fits in and leave the other parts out (for now).
For some parts I will request some additional info later (what the reason or the use case was for some changes).
Thanks for making this project better.

**Comment by breathbath** [comment]
Perfect, thanks as well. Please let me know about all your questions.

**Comment by Metabor** [comment]
Because I am preparing a new release (and have to bring up tests on a good level), I will come back to the other suggestions later.

**Pull request merged**
